algoritmo "semnome"
var
   contador, N1, N2: inteiro
inicio
      escreva ("Até que numero você quer contar? ")
      leia(N1)
      escreva ("Quer contar de quanto em quantos numeros?")
      leia(N2)
      contador <- 0
      enquanto (contador <= N1) faca
               escreval (contador)
               contador <- contador + N2
      fimenquanto
      escreval ("você terminou de contar!!")
fimalgoritmo
